import { formatCurrency } from '../utils/api';

export default function InvestmentConfirmationModal({ investment, investor, onClose }) {
  const { startup, amount, date, isFinalization } = investment;

  const handleDownloadReceipt = () => {
    // Generate receipt content
    const receiptContent = generateReceipt();

    // Create blob with UTF-8 encoding and proper line endings
    const blob = new Blob([receiptContent], { type: 'text/plain;charset=utf-8' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const timestamp = new Date().getTime();
    const fileName = `Investment-Receipt-${investor.id}-${timestamp}.txt`;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  const handlePrintReceipt = () => {
    const receiptWindow = window.open('', '_blank');
    const receiptHTML = generateReceiptHTML();

    receiptWindow.document.write(receiptHTML);
    receiptWindow.document.close();
    receiptWindow.focus();

    setTimeout(() => {
      receiptWindow.print();
    }, 250);
  };

  const generateReceipt = () => {
    const timestamp = new Date().toLocaleString('en-US', {
      dateStyle: 'full',
      timeStyle: 'long'
    });

    if (isFinalization) {
      const receipt = [
        '===============================================================',
        '              INVESTMENT PORTFOLIO CONFIRMATION',
        '===============================================================',
        '',
        `RECEIPT NUMBER: INV-${date.getTime()}`,
        `DATE & TIME: ${timestamp}`,
        '',
        '---------------------------------------------------------------',
        '                    INVESTOR INFORMATION',
        '---------------------------------------------------------------',
        '',
        `Investor Name:     ${investor.name}`,
        `Investor ID:       ${investor.id}`,
        'Account Status:    VIP EXECUTIVE',
        '',
        '---------------------------------------------------------------',
        '                   PORTFOLIO FINALIZATION',
        '---------------------------------------------------------------',
        '',
        `Total Capital:              ${formatCurrency(investor.starting_credit)}`,
        `Total Deployed:             ${formatCurrency(amount)}`,
        'Portfolio Status:           FINALIZED',
        '',
        '---------------------------------------------------------------',
        '                      IMPORTANT NOTICE',
        '---------------------------------------------------------------',
        '',
        'Your investment portfolio has been successfully finalized.',
        'This is an irreversible action. Your investments are now',
        'locked and cannot be modified.',
        '',
        'Thank you for your participation in the AUB Angel Investor',
        'Investment Hub.',
        '',
        '---------------------------------------------------------------',
        '',
        'This is an official confirmation receipt.',
        'Please retain this document for your records.',
        '',
        'Generated by: AUB Angel Investor Investment Hub',
        'Platform: VIP Executive Investment Portal',
        '',
        '==============================================================='
      ];
      return receipt.join('\n');
    }

    const receipt = [
      '===============================================================',
      '               INVESTMENT TRANSACTION RECEIPT',
      '===============================================================',
      '',
      `RECEIPT NUMBER: INV-${date.getTime()}`,
      `DATE & TIME: ${timestamp}`,
      '',
      '---------------------------------------------------------------',
      '                    INVESTOR INFORMATION',
      '---------------------------------------------------------------',
      '',
      `Investor Name:     ${investor.name}`,
      `Investor ID:       ${investor.id}`,
      'Account Status:    VIP EXECUTIVE',
      '',
      '---------------------------------------------------------------',
      '                  INVESTMENT DETAILS',
      '---------------------------------------------------------------',
      '',
      `Startup Name:      ${startup.name}`,
      `Industry:          ${startup.industry || 'N/A'}`,
      `Investment Amount: ${formatCurrency(amount)}`,
      '',
      '---------------------------------------------------------------',
      '                   PORTFOLIO SUMMARY',
      '---------------------------------------------------------------',
      '',
      `Total Capital:     ${formatCurrency(investor.starting_credit)}`,
      `Deployed Funds:    ${formatCurrency(investor.invested)}`,
      `Available Funds:   ${formatCurrency(investor.remaining)}`,
      '',
      '---------------------------------------------------------------',
      '',
      'This investment has been successfully processed and',
      'recorded in your portfolio.',
      '',
      'Thank you for your investment through the AUB Angel',
      'Investor Investment Hub.',
      '',
      '---------------------------------------------------------------',
      '',
      'This is an official transaction receipt.',
      'Please retain this document for your records.',
      '',
      'Generated by: AUB Angel Investor Investment Hub',
      'Platform: VIP Executive Investment Portal',
      '',
      '==============================================================='
    ];
    return receipt.join('\n');
  };

  const generateReceiptHTML = () => {
    const timestamp = new Date().toLocaleString('en-US', {
      dateStyle: 'full',
      timeStyle: 'long'
    });

    return `
<!DOCTYPE html>
<html>
<head>
  <title>Investment Receipt</title>
  <style>
    @page { margin: 2cm; }
    body {
      font-family: 'Courier New', monospace;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      background: white;
      color: #000;
    }
    .header {
      text-align: center;
      border-bottom: 3px double #000;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      font-size: 24px;
      margin: 0 0 10px 0;
      font-weight: bold;
    }
    .section {
      margin: 30px 0;
      border-bottom: 1px solid #ccc;
      padding-bottom: 20px;
    }
    .section h2 {
      font-size: 14px;
      margin: 0 0 15px 0;
      font-weight: bold;
      text-decoration: underline;
    }
    .row {
      display: flex;
      justify-content: space-between;
      margin: 8px 0;
      font-size: 12px;
    }
    .label {
      font-weight: bold;
    }
    .highlight {
      background: #f0f0f0;
      padding: 15px;
      margin: 20px 0;
      border-left: 4px solid #000;
      font-size: 12px;
    }
    .footer {
      text-align: center;
      margin-top: 40px;
      font-size: 10px;
      color: #666;
    }
    .receipt-id {
      text-align: center;
      font-size: 11px;
      margin: 20px 0;
      color: #666;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${isFinalization ? 'PORTFOLIO FINALIZATION CONFIRMATION' : 'INVESTMENT TRANSACTION RECEIPT'}</h1>
    <div>AUB Angel Investor Investment Hub</div>
  </div>

  <div class="receipt-id">
    <strong>Receipt #:</strong> INV-${date.getTime()}<br>
    <strong>Date:</strong> ${timestamp}
  </div>

  <div class="section">
    <h2>Investor Information</h2>
    <div class="row">
      <span class="label">Name:</span>
      <span>${investor.name}</span>
    </div>
    <div class="row">
      <span class="label">Investor ID:</span>
      <span>${investor.id}</span>
    </div>
    <div class="row">
      <span class="label">Account Status:</span>
      <span>VIP EXECUTIVE</span>
    </div>
  </div>

  ${!isFinalization ? `
  <div class="section">
    <h2>Investment Details</h2>
    <div class="row">
      <span class="label">Startup:</span>
      <span>${startup.name}</span>
    </div>
    <div class="row">
      <span class="label">Industry:</span>
      <span>${startup.industry || 'N/A'}</span>
    </div>
    <div class="row">
      <span class="label">Investment Amount:</span>
      <span><strong>${formatCurrency(amount)}</strong></span>
    </div>
  </div>
  ` : ''}

  <div class="section">
    <h2>Portfolio Summary</h2>
    <div class="row">
      <span class="label">Total Capital:</span>
      <span>${formatCurrency(investor.starting_credit)}</span>
    </div>
    <div class="row">
      <span class="label">Deployed Funds:</span>
      <span>${formatCurrency(investor.invested)}</span>
    </div>
    <div class="row">
      <span class="label">Available Funds:</span>
      <span>${formatCurrency(investor.remaining)}</span>
    </div>
    ${isFinalization ? `
    <div class="row">
      <span class="label">Status:</span>
      <span><strong>FINALIZED</strong></span>
    </div>
    ` : ''}
  </div>

  <div class="highlight">
    <strong>Important Notice:</strong><br><br>
    ${isFinalization
      ? 'Your investment portfolio has been successfully finalized. This is an irreversible action. Your investments are now locked and cannot be modified.'
      : 'This investment has been successfully processed and recorded in your portfolio. You may modify this investment until you finalize your portfolio.'
    }
  </div>

  <div class="footer">
    <p>This is an official ${isFinalization ? 'confirmation' : 'transaction'} receipt.</p>
    <p>Please retain this document for your records.</p>
    <p style="margin-top: 20px;">
      Generated by AUB Angel Investor Investment Hub<br>
      VIP Executive Investment Portal
    </p>
  </div>
</body>
</html>
    `;
  };

  return (
    <div className="modal-overlay flex items-center justify-center p-4 z-50">
      <div className="card-premium max-w-2xl w-full my-8 animate-fade-in">
        {/* Success Header */}
        <div className="text-center mb-8">
          <div className="w-20 h-20 mx-auto mb-6 bg-gradient-to-br from-emerald-500/20 to-green-500/20 rounded-full flex items-center justify-center border-2 border-emerald-500/30 shadow-lg shadow-emerald-500/20">
            <svg className="w-10 h-10 text-emerald-400 animate-pulse" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <h2 className="text-3xl md:text-4xl font-display font-bold text-gradient-executive bg-clip-text text-transparent bg-gradient-to-r from-emerald-400 to-green-600 mb-3">
            {isFinalization ? 'Portfolio Finalized!' : 'Investment Confirmed!'}
          </h2>
          <p className="text-slate-400">
            {isFinalization
              ? 'Your investment portfolio has been successfully finalized'
              : 'Your investment has been processed successfully'
            }
          </p>
        </div>

        {/* Receipt Details */}
        <div className="bg-slate-800/50 backdrop-blur-xl rounded-xl p-6 mb-6 border border-slate-700/50">
          <div className="flex items-center justify-between mb-6 pb-4 border-b border-slate-700/50">
            <span className="text-xs text-slate-500 uppercase tracking-wider font-bold">Receipt Details</span>
            <span className="text-xs text-slate-400 font-mono">INV-{date.getTime()}</span>
          </div>

          {/* Investor Info */}
          <div className="mb-6">
            <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-3">Investor Information</h3>
            <div className="space-y-2">
              <div className="flex justify-between">
                <span className="text-slate-500 text-sm">Name:</span>
                <span className="text-slate-200 font-semibold">{investor.name}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500 text-sm">Status:</span>
                <span className="text-blue-400 font-semibold">VIP Executive</span>
              </div>
            </div>
          </div>

          {/* Investment Details */}
          {!isFinalization && (
            <div className="mb-6">
              <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-3">Investment Details</h3>
              <div className="space-y-2">
                <div className="flex justify-between">
                  <span className="text-slate-500 text-sm">Startup:</span>
                  <span className="text-slate-200 font-semibold">{startup.name}</span>
                </div>
                {startup.industry && (
                  <div className="flex justify-between">
                    <span className="text-slate-500 text-sm">Industry:</span>
                    <span className="text-slate-200 font-semibold">{startup.industry}</span>
                  </div>
                )}
                <div className="flex justify-between">
                  <span className="text-slate-500 text-sm">Amount:</span>
                  <span className="text-emerald-400 font-bold text-lg">{formatCurrency(amount)}</span>
                </div>
              </div>
            </div>
          )}

          {/* Portfolio Summary */}
          <div>
            <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-3">Portfolio Summary</h3>
            <div className="space-y-2">
              <div className="flex justify-between">
                <span className="text-slate-500 text-sm">Total Capital:</span>
                <span className="text-slate-200 font-semibold">{formatCurrency(investor.starting_credit)}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500 text-sm">Deployed:</span>
                <span className="text-blue-400 font-semibold">{formatCurrency(investor.invested)}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500 text-sm">Available:</span>
                <span className="text-emerald-400 font-semibold">{formatCurrency(investor.remaining)}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Important Notice */}
        <div className="bg-gradient-to-r from-blue-500/10 to-indigo-500/10 border-2 border-blue-500/30 rounded-xl p-6 mb-6">
          <div className="flex gap-3">
            <svg className="w-6 h-6 text-blue-400 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
            </svg>
            <div>
              <h4 className="text-blue-300 font-bold mb-2">Important Notice</h4>
              <p className="text-sm text-slate-300 leading-relaxed">
                {isFinalization
                  ? 'Your investment portfolio has been finalized and locked. This action is irreversible. No further modifications can be made to your investments.'
                  : 'This investment has been successfully recorded in your portfolio. You may modify this investment at any time until you finalize your portfolio.'
                }
              </p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-3">
          <button
            onClick={handleDownloadReceipt}
            className="btn-secondary flex-1 flex items-center justify-center gap-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download Receipt
          </button>
          <button
            onClick={handlePrintReceipt}
            className="btn-secondary flex-1 flex items-center justify-center gap-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print Receipt
          </button>
          <button
            onClick={onClose}
            className="btn-executive flex-1"
          >
            Continue
          </button>
        </div>

        {/* Timestamp */}
        <div className="mt-6 text-center text-xs text-slate-600">
          Generated on {date.toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'long' })}
        </div>
      </div>
    </div>
  );
}
